fix(common): common_download_archive to use get compression

diff --git a/lib/common b/lib/common
--- a/lib/common
+++ b/lib/common
@@ -196,7 +196,13 @@ ___x_cmd_env_common_download_archive(){
         return 0
     fi
 
-    local archive_path="$___X_CMD_ENV_PATH/$candidate/archive/$candidate-$version.zip"
+    local compression
+    if ! compression="$(___x_cmd_env_run_if_exist get_compression "$candidate" "$version")"; then
+		env:error "Failed to get compression of $candidate $version."
+		return 1
+	fi
+
+    local archive_path="$___X_CMD_ENV_PATH/$candidate/archive/$candidate-$version.${compression:-zip}"
     mkdir -p "${archive_path%/*}"
     local download_url
     if ! download_url="$("___x_cmd_env_${candidate}_get_download_url" "$candidate" "$version")"; then
