refactor(common_install): use full_version

diff --git a/lib/common b/lib/common
--- a/lib/common
+++ b/lib/common
@@ -1,67 +1,12 @@
 # shellcheck shell=sh disable=SC2039,SC1090,SC3043,SC2263    # xrc
 
-# Section: full_version
+# Section: full_version ls_local ls_remote
 
 ___x_cmd_env_common_full_version(){
-    printf "%s\n" "$1"
+    printf "%s\n" "$2"
     return
 }
 
-# EndSection
-
-# Section: install, uninstall
-___x_cmd_env_common_install(){
-    local candidate="${1:?Provide canddidate}"
-    local version="${2:?Provide version}"
-
-    # TODO: full_version check
-    # local full_version
-    # if ! full_version=$(___x_cmd_env_run_common_if_notfound full_version "$candidate" "${version}"); then
-    #     env_log error "Version of $candidate not found: $version"
-    #     return 1
-    # fi
-
-    # TODO: version needs to be changed to full_ version
-    if ___x_cmd_env_util_is_version_installed "$candidate" "$version"; then
-        env_log error "Version of $candidate $version already installed"
-        return 1
-    fi
-
-    # TODO: version needs to be changed to full_ version
-    if ! ___x_cmd_env_run_common_if_notfound download "$candidate" "$version"; then
-        env_log info "Fail to install $candidate of version: $version."
-        return 1
-    fi
-
-    # TODO: version needs to be changed to full_ version
-    if ! ___x_cmd_env_run_common_if_notfound unpack "$candidate" "$version"; then
-        env_log info "Fail to unpack $candidate of version: $version."
-        return 1
-    fi
-
-    # TODO: version needs to be changed to full_ version
-    ___x_cmd_env_common_use "$candidate" "$version"
-    env_log info "Successfully installed $candidate $version"
-}
-
-___x_cmd_env_common_uninstall(){
-    local candidate="${1:?Provide candidate}"
-    local version="${2:?Provide the version}"
-    env_log info "Uninstalling $1 $2"
-
-    local candidate_path="$___X_CMD_ENV_PATH/${candidate}/versions/${version}"
-    if [ -d "$candidate_path" ]; then
-        rm -rf "${candidate_path}"
-    else
-        env_log  warn "This ${candidate} ${version} is no exist."
-        return 1
-    fi
-    x boot rc del "x-env-$candidate"
-    # TODO: remove the shims from $PATH
-}
-# EndSection
-
-# Section: ls_local ls_remote
 ___x_cmd_env_common_ls_local(){
     local candidate="${1:?Provide candidate}"
 	if [ -d "$___X_CMD_ENV_PATH/$candidate/versions" ]; then
@@ -193,6 +138,55 @@ ___x_cmd_env_common_current(){
     done
 
     # FIXME: If there is no in home directory, that you will get an error.
+}
+# EndSection
+
+# Section: install, uninstall
+___x_cmd_env_common_install(){
+    local candidate="${1:?Provide canddidate}"
+    local version="${2:?Provide version}"
+
+    local full_version
+    if ! full_version=$(___x_cmd_env_run_common_if_notfound full_version "$candidate" "${version}"); then
+        env_log error "Version of $candidate not found: $version"
+        return 1
+    fi
+    unset version
+
+    env_log info "Installing $candidate $full_version"
+    if ___x_cmd_env_util_is_version_installed "$candidate" "$full_version"; then
+        env_log error "Version of $candidate $version already installed"
+        return 1
+    fi
+
+    if ! ___x_cmd_env_run_common_if_notfound download "$candidate" "$full_version"; then
+        env_log info "Fail to install $candidate of version: $full_version."
+        return 1
+    fi
+
+    if ! ___x_cmd_env_run_common_if_notfound unpack "$candidate" "$full_version"; then
+        env_log info "Fail to unpack $candidate of version: $full_version."
+        return 1
+    fi
+
+    ___x_cmd_env_common_use "$candidate" "$full_version"
+    env_log info "Successfully installed $candidate $full_version"
+}
+
+___x_cmd_env_common_uninstall(){
+    local candidate="${1:?Provide candidate}"
+    local version="${2:?Provide the version}"
+    env_log info "Uninstalling $1 $2"
+
+    local candidate_path="$___X_CMD_ENV_PATH/${candidate}/versions/${version}"
+    if [ -d "$candidate_path" ]; then
+        rm -rf "${candidate_path}"
+    else
+        env_log  warn "This ${candidate} ${version} is no exist."
+        return 1
+    fi
+    x boot rc del "x-env-$candidate"
+    # TODO: remove the shims from $PATH
 }
 # EndSection
 
