...

diff --git a/lib/config b/lib/config
--- a/lib/config
+++ b/lib/config
@@ -20,14 +20,19 @@ A
 }
 
 ___x_cmd_env_config_save(){
-    local tgt="${1:-"$___X_CMD_ENV_VERSION_CONFIG_PATH"}"
+    ___x_cmd_env_config___write "$___X_CMD_ENV_VERSION_CONFIG"
+}
 
-    if ! x mkdirp "${tgt%/*}"; then
-        env:error "Couldn't create folder: ${tgt%/*}"
+___x_cmd_env_config___write(){
+    local configstr="${1:?Provide config string}"
+    local tgt="${2:-"$___X_CMD_ENV_VERSION_CONFIG_PATH"}"
+
+    if ! x touch "$tgt"; then
+        env:error "Couldn't create file: ${tgt}"
         return 1
     fi
 
-    printf "%s" "$___X_CMD_ENV_VERSION_CONFIG" > "$tgt"
+    printf "%s" "$1" > "$tgt"
 }
 
 ___x_cmd_env___configstr_set_(){
