...

diff --git a/lib/config b/lib/config
--- a/lib/config
+++ b/lib/config
@@ -9,6 +9,24 @@ ___x_cmd_env_config_load(){
     ___x_cmd_env_try "$@"
 }
 
+# set
+___x_cmd_env_config_set_(){
+    local tgt="${1:-"$___X_CMD_ENV_VERSION_CONFIG_PATH"}"
+    if [ "$tgt" = - ]; then
+        tgt="$___X_CMD_ENV_VERSION_CONFIG_PATH"
+    fi
+
+    if ! x ensuredir "${tgt%/*}"; then
+        env:error "Couldn't create folder: ${tgt%/*}"
+        return 1
+    fi
+
+    local str="${2:-"$___X_CMD_ENV_VERSION_CONFIG"}"
+    printf "%s" "$str" >"${1:?Provide config file}"
+}
+
+
+
 ___x_cmd_env_config_save(){
     local tgt="${1:-"$___X_CMD_ENV_VERSION_CONFIG_PATH"}"
     if [ "$tgt" = - ]; then
