...

diff --git a/lib/config b/lib/config
--- a/lib/config
+++ b/lib/config
@@ -9,6 +9,31 @@ ___x_cmd_env_config_apply(){
     ___x_cmd_env_config_apply_by_var
 }
 
+___x_cmd_env_config_apply_by_var(){
+    local line
+    local bin
+    local version
+    while read -r line; do
+        bin="${line%=*}"
+        version="${line#*=}"
+        x pkg setup "$bin" "$version"
+    done <<A
+$___X_CMD_ENV_VERSION_CONFIG
+A
+
+}
+
+___x_cmd_env_config_load(){
+    if ! ___X_CMD_ENV_VERSION_CONFIG="$(cat)"; then
+        pkg:error "Config file not found."
+    fi
+    ___x_cmd_env_config_apply "$@"
+}
+
+___x_cmd_env_config_save(){
+    printf "%s" "$___X_CMD_ENV_VERSION_CONFIG" >"${1:?Provide config file}"
+}
+
 ___x_cmd_env_config_add(){
     local bin
     local tmp
@@ -35,27 +60,3 @@ $i"
 
 }
 
-___x_cmd_env_config_apply_by_var(){
-    local line
-    local bin
-    local version
-    while read -r line; do
-        bin="${line%=*}"
-        version="${line#*=}"
-        x pkg setup "$bin" "$version"
-    done <<A
-$___X_CMD_ENV_VERSION_CONFIG
-A
-
-}
-
-___x_cmd_env_config_load(){
-    if ! ___X_CMD_ENV_VERSION_CONFIG="$(cat)"; then
-        pkg:error "Config file not found."
-    fi
-    ___x_cmd_env_config_apply "$@"
-}
-
-___x_cmd_env_config_save(){
-    printf "%s" "$___X_CMD_ENV_VERSION_CONFIG" >"${1:?Provide config file}"
-}
