...

diff --git a/lib/main b/lib/main
--- a/lib/main
+++ b/lib/main
@@ -23,7 +23,7 @@ ___x_cmd___env_pasre__pkg__version(){
             ;;
         *)
             ___X_CMD___ENV_PARSE_PKG="${1}"
-            ___X_CMD___ENV_PARSE_VERSION="$(___x_cmd_pkg default_version "$1")"
+            ___X_CMD___ENV_PARSE_VERSION="$(___x_cmd_pkg default_version "$1" 2>/dev/null)"
     esac
 }
 
@@ -32,7 +32,16 @@ ___x_cmd_env_use(){
     x:trace env/use
     ___x_cmd_env_try "$@" || return
 
-    ___x_cmd_env_config_set "$@"
+    local code="___x_cmd_env_config_set"
+    for i in "$@"; do
+        ___x_cmd___env_pasre__pkg__version "$i"
+        if [ -z "$___X_CMD___ENV_PARSE_VERSION" ]; then
+            env:warn "Not found $___X_CMD___ENV_PARSE_PKG version."
+            continue
+        fi
+        code="$code $___X_CMD___ENV_PARSE_PKG=$___X_CMD___ENV_PARSE_VERSION"
+    done
+    eval "$code"
 }
 
 
@@ -51,28 +60,32 @@ ___x_cmd_env_try(){
     local ___X_CMD___ENV_PARSE_PKG
     local ___X_CMD___ENV_PARSE_VERSION
 
+    local code="___x_cmd_env___configstr_set_ \"\$___X_CMD_ENV_VERSION_CONFIG_PATH\""
     for i in "$@"; do
         ___x_cmd___env_pasre__pkg__version "$i"
+        if [ -z "$___X_CMD___ENV_PARSE_VERSION" ]; then
+            env:warn "Not found $___X_CMD___ENV_PARSE_PKG version."
+            continue
+        fi
+
         env:info "Prepare $___X_CMD___ENV_PARSE_PKG $___X_CMD___ENV_PARSE_VERSION"
         if ! ___x_cmd_pkg install "$___X_CMD___ENV_PARSE_PKG" "$___X_CMD___ENV_PARSE_VERSION"; then
             env:error "Cannot install package: $___X_CMD___ENV_PARSE_PKG $___X_CMD___ENV_PARSE_VERSION"
             return 1
         fi
-    done
-
-    for i in "$@"; do
-        ___x_cmd___env_pasre__pkg__version "$i"
 
         ___x_cmd___env_store_prev "$___X_CMD___ENV_PARSE_PKG"
         env:debug "Try $___X_CMD___ENV_PARSE_PKG $___X_CMD___ENV_PARSE_VERSION"
         ___x_cmd_pkg deactivate "$___X_CMD___ENV_PARSE_PKG" 2>/dev/null
 
-        [ -n "$___X_CMD___ENV_PARSE_VERSION" ] || return 0
         ___x_cmd_pkg activate "$___X_CMD___ENV_PARSE_PKG" "$___X_CMD___ENV_PARSE_VERSION"
         ___x_cmd___env_store_current "$___X_CMD___ENV_PARSE_PKG" "$___X_CMD___ENV_PARSE_VERSION"
+        ___X_CMD_ENV_VERSION_CONFIG_TRY="$___X_CMD_ENV_VERSION_CONFIG_TRY
+$___X_CMD___ENV_PARSE_PKG=$___X_CMD___ENV_PARSE_VERSION"
+        code="$code $___X_CMD___ENV_PARSE_PKG=$___X_CMD___ENV_PARSE_VERSION"
     done
+    eval "$code"
 
-    ___x_cmd_env___configstr_set_ "$___X_CMD_ENV_VERSION_CONFIG_PATH" "$@"
     ___X_CMD_ENV_VERSION_CONFIG="$(___x_cmd_ldict_print ___X_CMD_ENV___CONFIGSTR_SET_)"
 }
 
@@ -84,7 +97,7 @@ ___x_cmd_env_untry(){
     local version
     local ___X_CMD_ENV_PREV
 
-    local code=___x_cmd_env___configstr_set_
+    local code="___x_cmd_env___configstr_set_ \"\$___X_CMD_ENV_VERSION_CONFIG_PATH\""
     for i in "$@"; do
         pkg_name="${i%=*}"
         ___x_cmd_pkg deactivate "$pkg_name"
@@ -98,6 +111,7 @@ ___x_cmd_env_untry(){
     done
 
     eval "$code"
+    ___X_CMD_ENV_VERSION_CONFIG="$(___x_cmd_ldict_print ___X_CMD_ENV___CONFIGSTR_SET_)"
 }
 
 # TODO: ~
@@ -106,6 +120,8 @@ ___x_cmd_env_which(){
     local bin_path
     for i in "$@"; do
         bin_path="$(___x_cmd_pkg xbin path "${i%=*}" "$(___x_cmd_env_get_version "$i")")"
+        bin_path="${bin_path%/*}"
+        [ -d "$bin_path" ] || continue
         printf "%s\n" "${bin_path%/*}"
     done
 }
