feat(env): update lsenv
link #I4YUOU

diff --git a/lib/main b/lib/main
--- a/lib/main
+++ b/lib/main
@@ -289,20 +289,26 @@ options:
 A
     param:run
 
-    local candidate="${1}"
-    if [ -z "$candidate" ]; then
-        ___x_cmd_env_main_download help
-        return 1
-    fi
+    # local candidate="${1}"
+    # if [ -z "$candidate" ]; then
+    #     ___x_cmd_env_main_download help
+    #     return 1
+    # fi
 
-    local version
-    if ! version="$(___x_cmd_env_run_common_if_notfound full_version "$candidate" "$2")"; then
-        env_log error "Version of $candidate not found: $version"
-        return 1
-    fi
-    shift 2
+    # local version
+    # if ! version="$(___x_cmd_env_run_common_if_notfound full_version "$candidate" "$2")"; then
+    #     env_log error "Version of $candidate not found: $version"
+    #     return 1
+    # fi
+    # shift 2
 
-    ___x_cmd_env_run_common_if_notfound download "$candidate" "$version" "$@"
+    xrc env/lib/app/lsenv && ___x_cmd_ui_lsenv
+
+    echo "___X_CMD_UI_LSENV_FINAL_COMMAND: $___X_CMD_UI_LSENV_FINAL_COMMAND"
+    echo "___X_CMD_UI_LSENV_CURRENT_CANDIDATE: $___X_CMD_UI_LSENV_CURRENT_CANDIDATE"
+    echo "___X_CMD_UI_LSENV_CURRENT_VERSION: $___X_CMD_UI_LSENV_CURRENT_VERSION"
+
+    # ___x_cmd_env_run_common_if_notfound download "$candidate" "$version" "$@"
 }
 
 ___x_cmd_env_main_which(){
