feat(common): if no candidate for 'x env current' then print all candidate verison

diff --git a/lib/main b/lib/main
--- a/lib/main
+++ b/lib/main
@@ -94,7 +94,7 @@ options:
 A
     param:run
 
-    local candidate="${1}"
+    local candidate="${1}"; shift
     if [ -z "$candidate" ]; then
         env:warn "No candidate specified"
         ___x_cmd_env_main_ls --help
@@ -104,8 +104,7 @@ A
     # TODO: 增加 本地简写版本对应关系 和 全局简写版本对应关系
     # TODO: V8 -> V8.2   --> (Remote) V8.6
     if [ -n "$remote" ] ; then
-        ___x_cmd_env_run_common_if_notfound ls_remote "$@"
-        # ___x_cmd_env_run_common_if_notfound gen "$candidate" "$@"
+        ___x_cmd_env_run_common_if_notfound ls_remote "$candidate" "$@"
         return
     fi
 
@@ -132,8 +131,8 @@ A
 
     local candidate="${1}"
     local version
-    if ! version="$(___x_cmd_env_run_common_if_notfound full_version_remote "$candidate" "$2")"; then
-        env:error "Version of $candidate not found: $version"
+    if ! version="$(___x_cmd_env_run_common_if_notfound full_version_local "$candidate" "$2")"; then
+        env:error "Version of $candidate local not found: ${version}${2}"
         return 1
     fi
     shift 2
@@ -156,7 +155,7 @@ A
     local candidate="${1}"
     local version
     if ! version="$(___x_cmd_env_run_common_if_notfound full_version_remote "$candidate" "$2")"; then
-        env:error "Version of $candidate not found: $version"
+        env:error "Version of $candidate local not found: ${version}${2}"
         return 1
     fi
 
@@ -175,6 +174,16 @@ ___x_cmd_env_main_ws(){
 
 # Section: current
 ___x_cmd_env_main_current(){
+    if [ $# -eq 0 ]; then
+        local version
+        ___x_cmd_env_candidate_all | while read -r candidate; do
+            if version="$(___x_cmd_env_run_common_if_notfound current "$candidate" 2>/dev/null)" ; then
+                printf "%s\t%s\n" "$candidate" "$version"
+            fi
+        done
+        return
+    fi
+
     param:scope "env"
     param:dsl <<A
 options:
@@ -189,7 +198,6 @@ A
 
 # Section: install, uninstall
 ___x_cmd_env_main_install(){
-    # TODO: You can do more better in #2 advise json
     param:scope "env"
     param:dsl <<A
 advise:
@@ -215,7 +223,7 @@ A
 
     local version
     if ! version="$(___x_cmd_env_run_common_if_notfound full_version_remote "$candidate" "$2")"; then
-        env:error "Version of $candidate not found: $version"
+        env:error "Version of $candidate not found: ${version}${2}"
         return 1
     fi
 
@@ -241,8 +249,9 @@ A
 
     local version
     version="${2:-"$(___x_cmd_env_run_common_if_notfound current "$candidate")"}"
+    version="$(___x_cmd_env_run_common_if_notfound full_version_local "$candidate" "$version")"
     if [ -z "$version" ] || [ "$version" = "system" ]; then
-        env:error "Version of $candidate was not installed by xenv: $version"
+        env:error "Version of $candidate was not installed by xenv: ${version}${2}"
         return 1
     fi
 
@@ -286,6 +295,7 @@ A
 }
 
 ___x_cmd_env_main_which(){
+
     param:scope "env"
     param:dsl <<A
 advise:
