update lsenv

diff --git a/lib/main b/lib/main
--- a/lib/main
+++ b/lib/main
@@ -225,27 +225,34 @@ options:
 A
     param:run
 
-    # local candidate="${1}"
-    # if [ -z "$candidate" ]; then
-    #     ___x_cmd_env_main_install help
-    #     return 1
-    # fi
+    local candidate="${1}"
+    if [ -z "$candidate" ]; then
+        # ___x_cmd_env_main_install help
+        # return 1
+        xrc env/lib/app/lsenv && ___x_cmd_ui_lsenv
 
-    local candidate
+        # echo "___X_CMD_UI_LSENV_FINAL_COMMAND: $___X_CMD_UI_LSENV_FINAL_COMMAND"
+        # echo "___X_CMD_UI_LSENV_CURRENT_CANDIDATE: $___X_CMD_UI_LSENV_CURRENT_CANDIDATE"
+        # echo "___X_CMD_UI_LSENV_CURRENT_VERSION: $___X_CMD_UI_LSENV_CURRENT_VERSION"
+
+        # TODO: how to use shims
+        if [ "$___X_CMD_UI_LSENV_FINAL_COMMAND" = "ENTER" ]; then
+            candidate="$___X_CMD_UI_LSENV_CURRENT_CANDIDATE"
+            local version="$___X_CMD_UI_LSENV_CURRENT_VERSION"
+            ___x_cmd_env_run_common_if_notfound install "$candidate" "$version" "$@"
+        fi
+        return 0
+
+    fi
+
     local version
-    xrc env/lib/app/lsenv && ___x_cmd_ui_lsenv
+    if ! version="$(___x_cmd_env_run_common_if_notfound full_version "$candidate" "$2")"; then
+        env_log error "Version of $candidate not found: $version"
+        return 1
+    fi
+    shift 2
 
-    echo "___X_CMD_UI_LSENV_FINAL_COMMAND:" "$___X_CMD_UI_LSENV_FINAL_COMMAND"
-    echo "___X_CMD_UI_LSENV_CURRENT_ITEM:" "$___X_CMD_UI_LSENV_CURRENT_ITEM"
-    # xrc env/lib/app/lsenv && ___x_cmd_ui_lsenv
-    # local version
-    # if ! version="$(___x_cmd_env_run_common_if_notfound full_version "$candidate" "$2")"; then
-    #     env_log error "Version of $candidate not found: $version"
-    #     return 1
-    # fi
-    # shift 2
-
-    # ___x_cmd_env_run_common_if_notfound install "$candidate" "$version" "$use_shims" "$@"
+    ___x_cmd_env_run_common_if_notfound install "$candidate" "$version" "$use_shims" "$@"
 }
 
 ___x_cmd_env_main_uninstall(){
