___x_cmd_env___var_add and ___x_cmd_env_get_version

diff --git a/lib/main b/lib/main
--- a/lib/main
+++ b/lib/main
@@ -4,14 +4,24 @@
 # python=1.3
 # "
 
+___x_cmd_env_get_version(){
+    local pkg_name="${1:?Provide pkg name}"
+    local version="${2:?Provide version}"
+    if [ "$version" != "$pkg_name" ]; then
+        printf "%s\n" "$version"
+    else
+        x pkg default_version "$pkg_name"
+    fi
+}
+
 
 ___x_cmd_env_prepare(){
     local i
-    env:info "env prepare: $*"
-
+    x:trace x/env
     for i in "$@"; do
-        if ! x pkg install "${i%=*}" "${i#*=}"; then
-            env:error "Cannot install package: $i"
+        pkg:info "env prepare: packname:${i%=*} version:$(___x_cmd_env_get_version "${i%=*}" "${i#*=}")"
+        if ! x pkg install "${i%=*}" "$(___x_cmd_env_get_version "${i%=*}" "${i#*=}")"; then
+            pkg:error "Cannot install package: $i"
             return 1;
         fi
     done
@@ -19,15 +29,16 @@ ___x_cmd_env_prepare(){
 
 ___x_cmd_env_try(){
     param:void
-
+    x:trace x/env
     ___x_cmd_env_prepare "$@" || return
-    ___x_cmd_env___var_add "$@"
+    ___X_CMD_ENV___VAR_ADD_NO_SETUP="" ___x_cmd_env___var_add "$@"
 }
 
 ___x_cmd_env_use(){
     param:void
-
-    ___x_cmd_env_try "$@"
+    x:trace x/env
+    # ___x_cmd_env_try "$@"
+    ___x_cmd_env_prepare "$@" || return
 
     local backup="$___X_CMD_ENV_VERSION_CONFIG"
     if [ -f "$___X_CMD_ENV_VERSION_CONFIG_PATH" ]; then
