move checksum code

diff --git a/lib/candidate/node b/lib/candidate/node
--- a/lib/candidate/node
+++ b/lib/candidate/node
@@ -6,6 +6,121 @@ ___X_CMD_ENV_NODE_PATH="$___X_CMD_ENV_PATH/node"
 
 # EndSection
 
+# Section: utils checksum
+
+___x_cmd_compute_checksum() {
+  local FILE
+  FILE="${1-}"
+  if [ -z "${FILE}" ]; then
+    env_log error 'Provided file to checksum is empty.'
+    return 2
+  elif ! [ -f "${FILE}" ]; then
+    env_log error 'Provided file to checksum does not exist.'
+    return 1
+  fi
+
+  if nvm_has_non_aliased "sha256sum"; then
+    env_log info 'Computing checksum with sha256sum'
+    command sha256sum "${FILE}" | command awk '{print $1}'
+  elif nvm_has_non_aliased "shasum"; then
+    env_log info 'Computing checksum with shasum -a 256'
+    command shasum -a 256 "${FILE}" | command awk '{print $1}'
+  elif nvm_has_non_aliased "sha256"; then
+    env_log info 'Computing checksum with sha256 -q'
+    command sha256 -q "${FILE}" | command awk '{print $1}'
+  elif nvm_has_non_aliased "gsha256sum"; then
+    env_log info 'Computing checksum with gsha256sum'
+    command gsha256sum "${FILE}" | command awk '{print $1}'
+  elif nvm_has_non_aliased "openssl"; then
+    env_log info 'Computing checksum with openssl dgst -sha256'
+    command openssl dgst -sha256 "${FILE}" | command awk '{print $NF}'
+  elif nvm_has_non_aliased "bssl"; then
+    env_log info 'Computing checksum with bssl sha256sum'
+    command bssl sha256sum "${FILE}" | command awk '{print $1}'
+  elif nvm_has_non_aliased "sha1sum"; then
+    env_log info 'Computing checksum with sha1sum'
+    command sha1sum "${FILE}" | command awk '{print $1}'
+  elif nvm_has_non_aliased "sha1"; then
+    env_log info 'Computing checksum with sha1 -q'
+    command sha1 -q "${FILE}"
+  fi
+}
+
+___x_cmd_compare_checksum() {
+  local FILE
+  FILE="${1-}"
+  if [ -z "${FILE}" ]; then
+    env_log error 'Provided file to checksum is empty.'
+    return 4
+  elif ! [ -f "${FILE}" ]; then
+    env_log error 'Provided file to checksum does not exist.'
+    return 3
+  fi
+
+  local COMPUTED_SUM
+  COMPUTED_SUM="$(___x_cmd_compute_checksum "${FILE}")"
+
+  local CHECKSUM
+  CHECKSUM="${2-}"
+  if [ -z "${CHECKSUM}" ]; then
+    env_log error 'Provided checksum to compare to is empty.'
+    return 2
+  fi
+
+  if [ -z "${COMPUTED_SUM}" ]; then
+    env_log error "Computed checksum of '${FILE}' is empty." # missing in raspberry pi binary
+    env_log error 'WARNING: Continuing *without checksum verification*'
+    return
+  elif [ "${COMPUTED_SUM}" != "${CHECKSUM}" ]; then
+    env_log error "Checksums do not match: '${COMPUTED_SUM}' found, '${CHECKSUM}' expected."
+    return 1
+  fi
+  env_log info 'Checksums matched!'
+}
+
+nvm_get_checksum_binary() {
+  if nvm_has_non_aliased 'sha256sum'; then
+    nvm_echo 'sha256sum'
+  elif nvm_has_non_aliased 'shasum'; then
+    nvm_echo 'shasum'
+  elif nvm_has_non_aliased 'sha256'; then
+    nvm_echo 'sha256'
+  elif nvm_has_non_aliased 'gsha256sum'; then
+    nvm_echo 'gsha256sum'
+  elif nvm_has_non_aliased 'openssl'; then
+    nvm_echo 'openssl'
+  elif nvm_has_non_aliased 'bssl'; then
+    nvm_echo 'bssl'
+  elif nvm_has_non_aliased 'sha1sum'; then
+    nvm_echo 'sha1sum'
+  elif nvm_has_non_aliased 'sha1'; then
+    nvm_echo 'sha1'
+  else
+    env_log error 'Unaliased sha256sum, shasum, sha256, gsha256sum, openssl, or bssl not found.'
+    env_log error 'Unaliased sha1sum or sha1 not found.'
+    return 1
+  fi
+}
+
+nvm_get_checksum_alg() {
+  local NVM_CHECKSUM_BIN
+  NVM_CHECKSUM_BIN="$(nvm_get_checksum_binary 2>/dev/null)"
+  case "${NVM_CHECKSUM_BIN-}" in
+    sha256sum | shasum | sha256 | gsha256sum | openssl | bssl)
+      nvm_echo 'sha-256'
+    ;;
+    sha1sum | sha1)
+      nvm_echo 'sha-1'
+    ;;
+    *)
+      nvm_get_checksum_binary
+      return $?
+    ;;
+  esac
+}
+
+# EndSection
+
 # Section: utils
 
 nvm_is_zsh() {
@@ -20,36 +135,16 @@ nvm_has() {
     type "${1-}" >/dev/null 2>&1
 }
 
-nvm_echo_with_colors() {
-  command printf %b\\n "$*" 2>/dev/null
-}
-
 nvm_grep() {
   GREP_OPTIONS='' command grep "$@"
-}
-
-# Traverse up in directory tree to find containing folder
-nvm_find_up() {
-    local path_
-    path_="${PWD}"
-    while [ "${path_}" != "" ] && [ ! -f "${path_}/${1-}" ]; do
-        path_=${path_%/*}
-    done
-    nvm_echo "${path_}"
 }
 
 nvm_node_prefix() {
     nvm_echo 'node'
 }
 
-nvm_get_mirror() {
-    case "${1}-${2}" in
-    node-std) nvm_echo "${NVM_NODEJS_ORG_MIRROR:-https://nodejs.org/dist}" ;;
-    *)
-        env_log error 'unknown type of node.js release'
-        return 1
-        ;;
-    esac
+___x_cmd_node_get_mirror() {
+    nvm_echo "${NVM_NODEJS_ORG_MIRROR:-https://nodejs.org/dist}" ;;
 }
 
 nvm_ensure_version_prefix() {
@@ -135,14 +230,8 @@ nvm_ls_remote_index_tab() {
         return 5
     fi
 
-    local FLAVOR
-    FLAVOR="${1-}"
-
-    local TYPE
-    TYPE="${2-}"
-
     local MIRROR
-    MIRROR="$(nvm_get_mirror "${FLAVOR}" "${TYPE}")"
+    MIRROR="$(___x_cmd_node_get_mirror)"
     if [ -z "${MIRROR}" ]; then
         return 3
     fi
@@ -962,71 +1051,21 @@ nvm_has_non_aliased() {
   nvm_has "${1-}" && ! nvm_is_alias "${1-}"
 }
 
-nvm_get_checksum_binary() {
-  if nvm_has_non_aliased 'sha256sum'; then
-    nvm_echo 'sha256sum'
-  elif nvm_has_non_aliased 'shasum'; then
-    nvm_echo 'shasum'
-  elif nvm_has_non_aliased 'sha256'; then
-    nvm_echo 'sha256'
-  elif nvm_has_non_aliased 'gsha256sum'; then
-    nvm_echo 'gsha256sum'
-  elif nvm_has_non_aliased 'openssl'; then
-    nvm_echo 'openssl'
-  elif nvm_has_non_aliased 'bssl'; then
-    nvm_echo 'bssl'
-  elif nvm_has_non_aliased 'sha1sum'; then
-    nvm_echo 'sha1sum'
-  elif nvm_has_non_aliased 'sha1'; then
-    nvm_echo 'sha1'
-  else
-    env_log error 'Unaliased sha256sum, shasum, sha256, gsha256sum, openssl, or bssl not found.'
-    env_log error 'Unaliased sha1sum or sha1 not found.'
-    return 1
-  fi
-}
-
-nvm_get_checksum_alg() {
-  local NVM_CHECKSUM_BIN
-  NVM_CHECKSUM_BIN="$(nvm_get_checksum_binary 2>/dev/null)"
-  case "${NVM_CHECKSUM_BIN-}" in
-    sha256sum | shasum | sha256 | gsha256sum | openssl | bssl)
-      nvm_echo 'sha-256'
-    ;;
-    sha1sum | sha1)
-      nvm_echo 'sha-1'
-    ;;
-    *)
-      nvm_get_checksum_binary
-      return $?
-    ;;
-  esac
-}
-
 nvm_get_checksum() {
-  local FLAVOR
-  case "${1-}" in
-    node) FLAVOR="${1}" ;;
-    *)
-      env_log error 'supported flavors: node'
-      return 2
-    ;;
-  esac
-
   local MIRROR
-  MIRROR="$(nvm_get_mirror "${FLAVOR}" "${2-}")"
+  MIRROR="$(___x_cmd_node_get_mirror)"
   if [ -z "${MIRROR}" ]; then
     return 1
   fi
 
   local SHASUMS_URL
   if [ "$(nvm_get_checksum_alg)" = 'sha-256' ]; then
-    SHASUMS_URL="${MIRROR}/${3}/SHASUMS256.txt"
+    SHASUMS_URL="${MIRROR}/${1}/SHASUMS256.txt"
   else
-    SHASUMS_URL="${MIRROR}/${3}/SHASUMS.txt"
+    SHASUMS_URL="${MIRROR}/${1}/SHASUMS.txt"
   fi
 
-  nvm_download -L -s "${SHASUMS_URL}" -o - | command awk "{ if (\"${4}.${5}\" == \$2) print \$1}"
+  nvm_download -L -s "${SHASUMS_URL}" -o - | command awk "{ if (\"${2}.${3}\" == \$2) print \$1}"
 }
 
 nvm_cache_dir() {
@@ -1045,86 +1084,7 @@ nvm_sanitize_path() {
   nvm_echo "${SANITIZED_PATH}"
 }
 
-nvm_compute_checksum() {
-  local FILE
-  FILE="${1-}"
-  if [ -z "${FILE}" ]; then
-    env_log error 'Provided file to checksum is empty.'
-    return 2
-  elif ! [ -f "${FILE}" ]; then
-    env_log error 'Provided file to checksum does not exist.'
-    return 1
-  fi
-
-  if nvm_has_non_aliased "sha256sum"; then
-    env_log info 'Computing checksum with sha256sum'
-    command sha256sum "${FILE}" | command awk '{print $1}'
-  elif nvm_has_non_aliased "shasum"; then
-    env_log info 'Computing checksum with shasum -a 256'
-    command shasum -a 256 "${FILE}" | command awk '{print $1}'
-  elif nvm_has_non_aliased "sha256"; then
-    env_log info 'Computing checksum with sha256 -q'
-    command sha256 -q "${FILE}" | command awk '{print $1}'
-  elif nvm_has_non_aliased "gsha256sum"; then
-    env_log info 'Computing checksum with gsha256sum'
-    command gsha256sum "${FILE}" | command awk '{print $1}'
-  elif nvm_has_non_aliased "openssl"; then
-    env_log info 'Computing checksum with openssl dgst -sha256'
-    command openssl dgst -sha256 "${FILE}" | command awk '{print $NF}'
-  elif nvm_has_non_aliased "bssl"; then
-    env_log info 'Computing checksum with bssl sha256sum'
-    command bssl sha256sum "${FILE}" | command awk '{print $1}'
-  elif nvm_has_non_aliased "sha1sum"; then
-    env_log info 'Computing checksum with sha1sum'
-    command sha1sum "${FILE}" | command awk '{print $1}'
-  elif nvm_has_non_aliased "sha1"; then
-    env_log info 'Computing checksum with sha1 -q'
-    command sha1 -q "${FILE}"
-  fi
-}
-
-nvm_compare_checksum() {
-  local FILE
-  FILE="${1-}"
-  if [ -z "${FILE}" ]; then
-    env_log error 'Provided file to checksum is empty.'
-    return 4
-  elif ! [ -f "${FILE}" ]; then
-    env_log error 'Provided file to checksum does not exist.'
-    return 3
-  fi
-
-  local COMPUTED_SUM
-  COMPUTED_SUM="$(nvm_compute_checksum "${FILE}")"
-
-  local CHECKSUM
-  CHECKSUM="${2-}"
-  if [ -z "${CHECKSUM}" ]; then
-    env_log error 'Provided checksum to compare to is empty.'
-    return 2
-  fi
-
-  if [ -z "${COMPUTED_SUM}" ]; then
-    env_log error "Computed checksum of '${FILE}' is empty." # missing in raspberry pi binary
-    env_log error 'WARNING: Continuing *without checksum verification*'
-    return
-  elif [ "${COMPUTED_SUM}" != "${CHECKSUM}" ]; then
-    env_log error "Checksums do not match: '${COMPUTED_SUM}' found, '${CHECKSUM}' expected."
-    return 1
-  fi
-  env_log info 'Checksums matched!'
-}
-
 nvm_download_artifact() {
-  local FLAVOR
-  case "${1-}" in
-    node) FLAVOR="${1}" ;;
-    *)
-      env_log error 'supported flavors: node'
-      return 1
-    ;;
-  esac
-
   local KIND
   case "${2-}" in
     binary | source) KIND="${2}" ;;
@@ -1134,11 +1094,8 @@ nvm_download_artifact() {
     ;;
   esac
 
-  local TYPE
-  TYPE="${3-}"
-
   local MIRROR
-  MIRROR="$(nvm_get_mirror "${FLAVOR}" "${TYPE}")"
+  MIRROR="$(___x_cmd_node_get_mirror)"
   if [ -z "${MIRROR}" ]; then
     return 2
   fi
@@ -1162,7 +1119,7 @@ nvm_download_artifact() {
   COMPRESSION="$(nvm_get_artifact_compression "${VERSION}")"
 
   local CHECKSUM
-  CHECKSUM="$(nvm_get_checksum "${FLAVOR}" "${TYPE}" "${VERSION}" "${SLUG}" "${COMPRESSION}")"
+  CHECKSUM="$(nvm_get_checksum "${VERSION}" "${SLUG}" "${COMPRESSION}")"
 
   local tmpdir
   if [ "${KIND}" = 'binary' ]; then
@@ -1188,12 +1145,12 @@ nvm_download_artifact() {
 
   if [ -r "${TARBALL}" ]; then
     env_log error "Local cache found: $(nvm_sanitize_path "${TARBALL}")"
-    if nvm_compare_checksum "${TARBALL}" "${CHECKSUM}" >/dev/null 2>&1; then
+    if ___x_cmd_compare_checksum "${TARBALL}" "${CHECKSUM}" >/dev/null 2>&1; then
       env_log error "Checksums match! Using existing downloaded archive $(nvm_sanitize_path "${TARBALL}")"
       nvm_echo "${TARBALL}"
       return 0
     fi
-    nvm_compare_checksum "${TARBALL}" "${CHECKSUM}"
+    ___x_cmd_compare_checksum "${TARBALL}" "${CHECKSUM}"
     env_log error "Checksum check failed!"
     env_log error "Removing the broken local cache..."
     command rm -rf "${TARBALL}"
@@ -1212,7 +1169,7 @@ nvm_download_artifact() {
     return 5
   fi
 
-  nvm_compare_checksum "${TARBALL}" "${CHECKSUM}" || (
+  ___x_cmd_compare_checksum "${TARBALL}" "${CHECKSUM}" || (
     command rm -rf "${tmpdir}/files"
     return 6
   )
@@ -1321,12 +1278,8 @@ nvm_install_binary() {
   if [ "${FLAVOR}" = 'node' ]; then
     NODE_OR_IOJS="${FLAVOR}"
   fi
-  if [ "${NVM_NO_PROGRESS-}" = "1" ]; then
-    # --silent, --show-error, use short option as @samrocketman mentions the compatibility issue.
-    PROGRESS_BAR="-sS"
-  else
-    PROGRESS_BAR="--progress-bar"
-  fi
+
+  PROGRESS_BAR="--progress-bar"
   env_log info "Downloading and installing ${NODE_OR_IOJS-} ${VERSION}..."
   TARBALL="$(PROGRESS_BAR="${PROGRESS_BAR}" nvm_download_artifact "${FLAVOR}" binary "${TYPE-}" "${VERSION}" | command tail -1)"
   if [ -f "${TARBALL}" ]; then
@@ -1497,12 +1450,7 @@ nvm_install_source() {
   local TMPDIR_NVM
   local VERSION_PATH
 
-  if [ "${NVM_NO_PROGRESS-}" = "1" ]; then
-    # --silent, --show-error, use short option as @samrocketman mentions the compatibility issue.
-    PROGRESS_BAR="-sS"
-  else
-    PROGRESS_BAR="--progress-bar"
-  fi
+  PROGRESS_BAR="--progress-bar"
 
   nvm_is_zsh && setopt local_options shwordsplit
 
@@ -1588,39 +1536,29 @@ ___x_cmd_env_node_ls(){
 
 ___x_cmd_env_node_download() {
     local provided_version="${1:?Provide version}";shift
-    local version_not_provided=0
 
-    local nobinary
-    local nosource
-    local noprogress
-    nobinary=0
-    noprogress=0
-    nosource=0
     local ALIAS
     local PROVIDED_REINSTALL_PACKAGES_FROM
     local SKIP_DEFAULT_PACKAGES
     local DEFAULT_PACKAGES
 
-    VERSION=$(NVM_VERSION_ONLY=true NVM_LTS="${LTS-}" nvm_remote_version "${provided_version}")
+    VERSION=$(NVM_VERSION_ONLY=true nvm_remote_version "${provided_version}")
 
     if [ "${VERSION}" = 'N/A' ]; then
         env_log error "Version '${provided_version}' not found - try to browse available versions."
         return 3
     fi
 
-    local FLAVOR
-    FLAVOR="$(nvm_node_prefix)"
-
     if nvm_is_version_installed "${VERSION}"; then
         env_log error "${VERSION} is already installed."
         nvm_ensure_default_set "${provided_version}"
-
         return $?
     fi
 
     local EXIT_CODE
     EXIT_CODE=-1
 
+    local nobinary=0
     if [ "_${NVM_OS}" = "_freebsd" ]; then
       # node.js and io.js do not have a FreeBSD binary
       nobinary=1
@@ -1638,8 +1576,9 @@ ___x_cmd_env_node_download() {
     fi
 
     # skip binary install if "nobinary" option specified.
+    local nosource=0
     if [ $nobinary -ne 1 ] && nvm_binary_available "${VERSION}"; then
-      NVM_NO_PROGRESS="${NVM_NO_PROGRESS:-${noprogress}}" nvm_install_binary "${FLAVOR}" std "${VERSION}" "${nosource}"
+      nvm_install_binary "node" std "${VERSION}" "${nosource}"
       EXIT_CODE=$?
     fi
 
@@ -1652,7 +1591,7 @@ ___x_cmd_env_node_download() {
         env_log error 'Installing from source on non-WSL Windows is not supported'
         EXIT_CODE=87
       else
-        NVM_NO_PROGRESS="${NVM_NO_PROGRESS:-${noprogress}}" nvm_install_source "${FLAVOR}" std "${VERSION}" "${NVM_MAKE_JOBS}"
+        nvm_install_source node std "${VERSION}" "${NVM_MAKE_JOBS}"
         EXIT_CODE=$?
       fi
     fi
