refactor: change some varname,such as archive_dir_files -> archive_unpack_files
link #I4VRUH

diff --git a/lib/candidate/node b/lib/candidate/node
--- a/lib/candidate/node
+++ b/lib/candidate/node
@@ -13,17 +13,19 @@ ___x_cmd_env_node_sort_versions(){
 }
 
 ___x_cmd_env_node_version_greater_than_or_equal_to() {
-  command awk 'BEGIN {
-    if (ARGV[1] == "" || ARGV[2] == "") exit(1)
-    split(ARGV[1], a, /\./);
-    split(ARGV[2], b, /\./);
-    for (i=1; i<=3; i++) {
-      if (a[i] && a[i] !~ /^[0-9]+$/) exit(2);
-      if (a[i] < b[i]) exit(3);
-      else if (a[i] > b[i]) exit(0);
-    }
-    exit(0)
-  }' "${1#v}" "${2#v}"
+    local version1="${1#v}"
+    local version2="${2#v}"
+    command awk 'BEGIN {
+        if (ARGV[1] == "" || ARGV[2] == "") exit(1)
+        split(ARGV[1], a, /\./);
+        split(ARGV[2], b, /\./);
+        for (i=1; i<=3; i++) {
+        if (a[i] && a[i] !~ /^[0-9]+$/) exit(2);
+        if (a[i] < b[i]) exit(3);
+        else if (a[i] > b[i]) exit(0);
+        }
+        exit(0)
+    }' "${version1}" "${version2}"
 }
 
 # EndSection
@@ -91,15 +93,14 @@ A
 
     local slug="node-${version}-${platform}-${arch}"
     local compression='tar.gz'; [ "${platform}" = 'win' ] && compression='zip' # TODO: tar.xz support
-    local archive_dir="$___X_CMD_ENV_PATH/node/archive"
-    mkdir -p "${archive_dir}"
-    local archive_path="${archive_dir}/node-${version}.${compression}"
+    local archive_path="$___X_CMD_ENV_PATH/node/archive/node-${version}.${compression}"
+    mkdir -p "$(dirname "$archive_path")"
 
     # TODO: node <= 0.1.13 does not have a directory
     local archive_url="${___X_CMD_ENV_NODE_MIRROR}/${version}/${slug}.${compression}"
     if ! curl -L -C - --progress-bar "${archive_url}" -o "${archive_path}"; then
         rm -rf "${archive_path}"
-        env_log error "Binary download from ${archive_url} failed, trying source."
+        env_log error "Download from ${archive_url} failed."
         return 1
     fi
 
@@ -113,10 +114,10 @@ A
 ___x_cmd_env_node_unpack_win(){
     local version_path="${___X_CMD_ENV_PATH}/node/versions/${version}/bin"
 
-    unzip -q "${archive_path}" -d "${archive_dir_files}" || return 1
+    unzip -q "${archive_path}" -d "${archive_unpack_files}" || return 1
 
     mkdir -p "${version_path}" && (
-        mv "${archive_dir_files}/"*/* "${version_path}" || return 1
+        mv "${archive_unpack_files}/"*/* "${version_path}" || return 1
         cd "${version_path}" && chmod +x node.exe npm npx
         # chmod +x "${version_path}"/npx 2>/dev/null
     )
@@ -124,9 +125,8 @@ ___x_cmd_env_node_unpack_win(){
 
 ___x_cmd_env_node_unpack_other(){
     local version_path="${___X_CMD_ENV_PATH}/node/versions/${version}"
-    tar -xzf "${archive_path}" -C "${archive_dir_files}" --strip-components 1 || return 1
-
-    mkdir -p "${version_path}" && mv "${archive_dir_files}/"* "${version_path}"
+    tar -xzf "${archive_path}" -C "${archive_unpack_files}" --strip-components 1 || return 1
+    mkdir -p "${version_path}" && mv "${archive_unpack_files}/"* "${version_path}"
 }
 
 ___x_cmd_env_node_unpack(){
@@ -141,11 +141,10 @@ $(x os name; x os arch)
 A
     local compression='tar.gz'; [ "${platform}" = 'win' ] && compression='zip' # TODO: tar.xz support
     local archive_path="$___X_CMD_ENV_PATH/node/archive/node-${version}.${compression}"
-    local archive_dir_files
 
-
-    archive_dir_files="$(dirname "$archive_path")/files"
-    mkdir -p "$archive_dir_files"
+    local archive_unpack_files
+    archive_unpack_files="$(dirname "$archive_path")/files"
+    mkdir -p "$archive_unpack_files"
 
     case "$platform" in
         win)    ___x_cmd_env_node_unpack_win    ;;
@@ -153,7 +152,7 @@ A
     esac
     local code=$?
 
-    rm -rf "${archive_dir_files}"
+    rm -rf "${archive_unpack_files}"
     env_log info "Done unpacking!"
     return $code
 }
