Debug node

diff --git a/lib/candidate/node b/lib/candidate/node
--- a/lib/candidate/node
+++ b/lib/candidate/node
@@ -8,7 +8,7 @@ ___X_CMD_ENV_NODE_MIRROR="https://nodejs.org/dist"
 
 # Section: full_version, ls_remote
 ___x_cmd_env_node_full_version(){
-    ___x_cmd_env_node_ls_remote "${1:?Provide node version pattern}" "$2" | awk 'END{ if (NR<=0) { exit(1) } else print $1;   }'
+    ___x_cmd_env_node_ls_remote "${1:?Provide node version pattern}" "$2" | awk 'END{ if (NR<=0) { exit(1) } else print $1;}'
 }
 
 ___x_cmd_env_node_ls_remote(){
@@ -35,16 +35,16 @@ ___x_cmd_env_node_ls_remote(){
 
 ___x_cmd_env_node_download(){
     local version="${1:?Provide node version}"
-    local full_version
-    if full_version=$(___x_cmd_env_node_full_version "${version}" -); then
-        env_log error "Version '${version}' not found $full_version. "
+    if ! full_version=$(___x_cmd_env_node_full_version "${version}"); then
+        env_log error "Version '${version}' not found: $full_version. "
         return 1
     fi
-
-    if ___x_cmd_env_common_util_is_archieve_cached node "$full_version"; then
-        env_log info "Archieve existed: $full_version"
-        return 0
-    fi
+    # TODO: Check if it is installed
+    # TODO: Check if the installation package exists
+    # if ___x_cmd_env_util_is_archieve_cached node "$full_version"; then
+    #     env_log info "Archieve existed: $full_version"
+    #     return 0
+    # fi
 
     # TODO: Check if version is already downloaded
     # TODO: Handle bsd, sunos ..
@@ -62,11 +62,13 @@ ___x_cmd_env_node_download(){
 $(x os name; printf "\n"; x os arch)
 A
 
-    local archieve_dir="$___X_CMD_ENV_PATH/node/cache/bin/${slug}"
     local slug="node-${full_version}-${platform}-${arch}"
     local compression='tar.gz'; [ "${platform}" = 'win' ] && compression='zip' # TODO: tar.xz support
+    local archieve_dir="$___X_CMD_ENV_PATH/node/cache/bin/${slug}"
+    archieve_dir_files="${archieve_dir}/files"
+    mkdir -p "${archieve_dir_files}"
 
-    local tarball="${archieve_dir}/${slug}.${compression}"
+    tarball="${archieve_dir}/${slug}.${compression}"
 
     # TODO: node <= 0.1.13 does not have a directory
     local tarball_url="${___X_CMD_ENV_NODE_MIRROR}/${full_version}/${slug}.${compression}"
@@ -95,16 +97,14 @@ ___x_cmd_env_node_unpack_win(){
 }
 
 ___x_cmd_env_node_unpack_other(){
+    local version_path="${___X_CMD_ENV_PATH}/node/versions/${full_version}"
     tar -xzf "${tarball}" -C "${archieve_dir_files}" --strip-components 1 || return 1
 
-    local version_path="${___X_CMD_ENV_PATH}/node/versions/${full_version}"
     mkdir -p "${version_path}" && mv "${archieve_dir_files}/"* "${version_path}"
 }
 
 ___x_cmd_env_node_unpack(){
     # TODO: checksum
-    local archieve_dir_files="${archieve_dir}/files"
-    mkdir -p "${archieve_dir_files}"
 
     case "$platform" in
         win)    ___x_cmd_env_node_unpack_win    ;;
@@ -113,6 +113,7 @@ ___x_cmd_env_node_unpack(){
     local code=$?
 
     rm -rf "${archieve_dir_files}"
+    env_log info "Done unpacking!"
     return $code
 }
 
diff --git a/lib/common b/lib/common
--- a/lib/common
+++ b/lib/common
@@ -14,11 +14,12 @@ ___x_cmd_env_common_install(){
     local candidate="${1:?Provide canddidate}"
     local version="${2:?Provide version}"
 
-    local full_version
-    if ! full_version=$(___x_cmd_env_run_common_if_notfound full_version "$candidate" "${version}"); then
-        env_log error "Version of $candidate not found: $version"
-        return 1
-    fi
+    # TODO: full_version check
+    # local full_version
+    # if ! full_version=$(___x_cmd_env_run_common_if_notfound full_version "$candidate" "${version}"); then
+    #     env_log error "Version of $candidate not found: $version"
+    #     return 1
+    # fi
 
     # TODO: version needs to be changed to full_ version
     if ___x_cmd_env_util_is_version_installed "$candidate" "$version"; then
@@ -115,7 +116,7 @@ ___x_cmd_env_shim_dir(){
     rm -rf "${___X_CMD_ENV_PATH}/$candidate/shims"
     mkdir -p "${___X_CMD_ENV_PATH}/$candidate/shims"
 
-    for name in $versions_path/${version}/bin/* ; do
+    for name in "${versions_path}/${version}/bin/"* ; do
         printf "%s" "$(cat <<A
 #!/usr/bin/env sh
 set -e
