remove LTS

diff --git a/lib/candidate/node b/lib/candidate/node
--- a/lib/candidate/node
+++ b/lib/candidate/node
@@ -771,11 +771,11 @@ nvm_remote_version() {
     if nvm_validate_implicit_alias "${PATTERN}" 2>/dev/null; then
         case "${PATTERN}" in
         *)
-            VERSION="$(NVM_LTS="${NVM_LTS-}" nvm_ls_remote "${PATTERN}")" && :
+            VERSION="$(nvm_ls_remote "${PATTERN}")" && :
             ;;
         esac
     else
-        VERSION="$(NVM_LTS="${NVM_LTS-}" nvm_remote_versions "${PATTERN}" | command tail -1)"
+        VERSION="$(nvm_remote_versions "${PATTERN}" | command tail -1)"
     fi
     if [ -n "${NVM_VERSION_ONLY-}" ]; then
         command awk 'BEGIN {
@@ -1587,12 +1587,8 @@ ___x_cmd_env_node_ls(){
 # Section: node download, install
 
 ___x_cmd_env_node_download() {
-    local provided_version="${1-}"
+    local provided_version="${1:?Provide version}";shift
     local version_not_provided=0
-
-    if [ $# -lt 1 ]; then
-        version_not_provided=1
-    fi
 
     local nobinary
     local nosource
@@ -1600,7 +1596,6 @@ ___x_cmd_env_node_download() {
     nobinary=0
     noprogress=0
     nosource=0
-    local LTS
     local ALIAS
     local NVM_UPGRADE_NPM
     NVM_UPGRADE_NPM=1
@@ -1610,49 +1605,10 @@ ___x_cmd_env_node_download() {
     local SKIP_DEFAULT_PACKAGES
     local DEFAULT_PACKAGES
 
-    if [ -z "${provided_version}" ]; then
-        if [ "_${LTS-}" = '_*' ]; then
-            nvm_echo 'Installing latest LTS version.'
-            if [ $# -gt 0 ]; then
-                shift
-            fi
-        elif [ "_${LTS-}" != '_' ]; then
-            nvm_echo "Installing with latest version of LTS line: ${LTS}"
-            if [ $# -gt 0 ]; then
-                shift
-            fi
-        else
-            return 127
-        fi
-    elif [ $# -gt 0 ]; then
-        shift
-    fi
-
-    case "${provided_version}" in
-    'lts/*')
-        LTS='*'
-        provided_version=''
-        ;;
-    lts/*)
-        LTS="${provided_version##lts/}"
-        provided_version=''
-        ;;
-    esac
     VERSION=$(NVM_VERSION_ONLY=true NVM_LTS="${LTS-}" nvm_remote_version "${provided_version}")
 
     if [ "${VERSION}" = 'N/A' ]; then
-        local LTS_MSG
-        local REMOTE_CMD
-        if [ "${LTS-}" = '*' ]; then
-            LTS_MSG='(with LTS filter) '
-            REMOTE_CMD='nvm ls-remote --lts'
-        elif [ -n "${LTS-}" ]; then
-            LTS_MSG="(with LTS filter '${LTS}') "
-            REMOTE_CMD="nvm ls-remote --lts=${LTS}"
-        else
-            REMOTE_CMD='nvm ls-remote'
-        fi
-        env_log error "Version '${provided_version}' ${LTS_MSG-}not found - try \`${REMOTE_CMD}\` to browse available versions."
+        env_log error "Version '${provided_version}' not found - try to browse available versions."
         return 3
     fi
 
@@ -1672,12 +1628,7 @@ ___x_cmd_env_node_download() {
 
     if nvm_is_version_installed "${VERSION}"; then
         env_log error "${VERSION} is already installed."
-        if [ -n "${LTS-}" ]; then
-          LTS="$(print "${LTS}" | tr '[:upper:]' '[:lower:]')"
-          nvm_ensure_default_set "lts/${LTS}"
-        else
-          nvm_ensure_default_set "${provided_version}"
-        fi
+        nvm_ensure_default_set "${provided_version}"
 
         return $?
     fi
@@ -1685,72 +1636,44 @@ ___x_cmd_env_node_download() {
     local EXIT_CODE
     EXIT_CODE=-1
 
-    if [ -n "${NVM_INSTALL_THIRD_PARTY_HOOK-}" ]; then
-        env_log error '** $NVM_INSTALL_THIRD_PARTY_HOOK env var set; dispatching to third-party installation method **'
-        local NVM_METHOD_PREFERENCE
-        NVM_METHOD_PREFERENCE='binary'
-        if [ $nobinary -eq 1 ]; then
-          NVM_METHOD_PREFERENCE='source'
-        fi
+    if [ "_${NVM_OS}" = "_freebsd" ]; then
+      # node.js and io.js do not have a FreeBSD binary
+      nobinary=1
+      env_log error "Currently, there is no binary for FreeBSD"
+    elif [ "_$NVM_OS" = "_openbsd" ]; then
+      # node.js and io.js do not have a OpenBSD binary
+      nobinary=1
+      env_log error "Currently, there is no binary for OpenBSD"
+    elif [ "_${NVM_OS}" = "_sunos" ]; then
+      # Not all node/io.js versions have a Solaris binary
+      if ! nvm_has_solaris_binary "${VERSION}"; then
+        nobinary=1
+        env_log error "Currently, there is no binary of version ${VERSION} for SunOS"
+      fi
+    fi
 
-        local VERSION_PATH
-        VERSION_PATH="$(nvm_version_path "${VERSION}")"
-        "${NVM_INSTALL_THIRD_PARTY_HOOK}" "${VERSION}" "${FLAVOR}" std "${NVM_METHOD_PREFERENCE}" "${VERSION_PATH}" || {
-          EXIT_CODE=$?
-          env_log error '*** Third-party $NVM_INSTALL_THIRD_PARTY_HOOK env var failed to install! ***'
-          return $EXIT_CODE
-        }
-        if ! nvm_is_version_installed "${VERSION}"; then
-          env_log error '*** Third-party $NVM_INSTALL_THIRD_PARTY_HOOK env var claimed to succeed, but failed to install! ***'
-          return 33
-        fi
-        EXIT_CODE=0
-    else
+    # skip binary install if "nobinary" option specified.
+    if [ $nobinary -ne 1 ] && nvm_binary_available "${VERSION}"; then
+      NVM_NO_PROGRESS="${NVM_NO_PROGRESS:-${noprogress}}" nvm_install_binary "${FLAVOR}" std "${VERSION}" "${nosource}"
+      EXIT_CODE=$?
+    fi
 
-        if [ "_${NVM_OS}" = "_freebsd" ]; then
-          # node.js and io.js do not have a FreeBSD binary
-          nobinary=1
-          env_log error "Currently, there is no binary for FreeBSD"
-        elif [ "_$NVM_OS" = "_openbsd" ]; then
-          # node.js and io.js do not have a OpenBSD binary
-          nobinary=1
-          env_log error "Currently, there is no binary for OpenBSD"
-        elif [ "_${NVM_OS}" = "_sunos" ]; then
-          # Not all node/io.js versions have a Solaris binary
-          if ! nvm_has_solaris_binary "${VERSION}"; then
-            nobinary=1
-            env_log error "Currently, there is no binary of version ${VERSION} for SunOS"
-          fi
-        fi
+    if [ $EXIT_CODE -ne 0 ]; then
+      if [ -z "${NVM_MAKE_JOBS-}" ]; then
+        nvm_get_make_jobs
+      fi
 
-        # skip binary install if "nobinary" option specified.
-        if [ $nobinary -ne 1 ] && nvm_binary_available "${VERSION}"; then
-          NVM_NO_PROGRESS="${NVM_NO_PROGRESS:-${noprogress}}" nvm_install_binary "${FLAVOR}" std "${VERSION}" "${nosource}"
-          EXIT_CODE=$?
-        fi
-
-        if [ $EXIT_CODE -ne 0 ]; then
-          if [ -z "${NVM_MAKE_JOBS-}" ]; then
-            nvm_get_make_jobs
-          fi
-
-          if [ "_${NVM_OS}" = "_win" ]; then
-            env_log error 'Installing from source on non-WSL Windows is not supported'
-            EXIT_CODE=87
-          else
-            NVM_NO_PROGRESS="${NVM_NO_PROGRESS:-${noprogress}}" nvm_install_source "${FLAVOR}" std "${VERSION}" "${NVM_MAKE_JOBS}" "${ADDITIONAL_PARAMETERS}"
-            EXIT_CODE=$?
-          fi
-        fi
-
+      if [ "_${NVM_OS}" = "_win" ]; then
+        env_log error 'Installing from source on non-WSL Windows is not supported'
+        EXIT_CODE=87
+      else
+        NVM_NO_PROGRESS="${NVM_NO_PROGRESS:-${noprogress}}" nvm_install_source "${FLAVOR}" std "${VERSION}" "${NVM_MAKE_JOBS}" "${ADDITIONAL_PARAMETERS}"
+        EXIT_CODE=$?
+      fi
     fi
 
     if [ $EXIT_CODE -eq 0 ] && nvm_install_npm_if_needed "${VERSION}"; then
-        if [ -n "${LTS-}" ]; then
-          nvm_ensure_default_set "lts/${LTS}"
-        else
-          nvm_ensure_default_set "${provided_version}"
-        fi
+        nvm_ensure_default_set "${provided_version}"
         # if [ "${NVM_UPGRADE_NPM}" = 1 ]; then
         #   nvm install-latest-npm
         #   EXIT_CODE=$?
