go

diff --git a/lib/candidate/perl b/lib/candidate/perl
--- a/lib/candidate/perl
+++ b/lib/candidate/perl
@@ -1,45 +1,34 @@
 # shellcheck shell=sh disable=SC2039,SC1090,SC3043,SC2263    # xrc
 
-___x_cmd_env_go_ls(){
-    :
+___x_cmd_env_perl_ls_remote(){
+    local cache_path="$___X_CMD_ENV_PATH/pearl/cache/version_list"
+    local cache_expiration=${2:-1}
+
+    ___x_cmd_httpget "https://www.cpan.org/src/README.html" "$cache_path" "$cache_expiration" 2>/dev/null && \
+        awk 'match($0, /<td>5/){gsub(/^[ ]+/,"",$0);gsub(/<t[\/]?d>/,"",$0);gsub(/<\/td>/,"",$0);print $0}' < "$cache_path"
 }
 
-___x_cmd_env_go_la(){
-    :
+___x_cmd_env_perl_download_archive(){
+    local version=${1:?Provide a version}
+
+	if ___x_cmd_env_util_is_archive_cached perl "$version" 2>/dev/null; then
+		env_log info  "Archive existed: $version"
+		return 0
+	fi
+    mkdir -p "$(dirname "${archive_path}")"
+    local archive_path=$___X_CMD_ENV_PATH/perl/archive/perl-${version}.tar.gz
+    env_log info "Downloading perl-${version}"
+
+    download_url="https://www.cpan.org/src/5.0/perl-${version}.tar.gz"
+
+    if ! curl --progress-bar --location --retry-max-time 10 --retry 0 "$download_url" --output "$archive_path" ; then
+        env_log error "Download failure from $download_url"
+        return 1
+    fi
+        env_log info "Download Successfully"
+
 }
 
-___x_cmd_env_go_download(){
-    :
-}
+___x_cmd_env_perl_unpack(){
 
-___x_cmd_env_go_install(){
-    :
-}
-
-___x_cmd_env_go_uninstall(){
-    :
-}
-
-___x_cmd_env_go_try(){
-    :
-}
-
-___x_cmd_env_go_use(){
-    :
-}
-
-___x_cmd_env_go_ws(){
-    :
-}
-
-___x_cmd_env_go_current(){
-    :
-}
-
-___x_cmd_env_go_which(){
-    :
-}
-
-___x_cmd_env_go_exec(){
-    :
 }
