refactor: update python
link #I4VRUH

diff --git a/lib/candidate/python b/lib/candidate/python
--- a/lib/candidate/python
+++ b/lib/candidate/python
@@ -19,21 +19,19 @@ ___x_cmd_env_python_get_system_platform(){
     esac
 }
 
-___x_cmd_env_python_get_miniconda_name_and_filename(){
+___x_cmd_env_python_get_miniconda_filename_and_compression(){
     local version="${1:?Provide python version}"
 
     local platform
     local system
     ___x_cmd_env_python_get_system_platform
 
-    miniconda_name="Miniconda3-${version}-${system}-${platform}"
     if [ $system = "Windows" ] ; then
-        miniconda_filename="${miniconda_name}.exe"
-        archive_name="python-${version}.exe"
+        compression="exe"
     else
-        miniconda_filename="${miniconda_name}.sh"
-        archive_name="python-${version}.sh"
+        compression="sh"
     fi
+    miniconda_filename="Miniconda3-${version}-${system}-${platform}.${compression}"
 }
 
 # EndSection
@@ -63,49 +61,48 @@ ___x_cmd_env_python_ls_remote(){
 
 # Section: download, unpack
 
-___x_cmd_env_python_download_archive()(
-    local miniconda_name
-    local miniconda_filename
-    local archive_name
+___x_cmd_env_python_download_archive(){
     local version="${1:?Provide python version}"
 
     if ___x_cmd_env_util_is_archive_cached python "$version" 2>/dev/null; then
         env_log info "Archive existed: $version"
-    else
-        ___x_cmd_env_python_get_miniconda_name_and_filename "$version"
-
-        local candidate_path="$___X_CMD_ENV_PATH/python/archive"
-        mkdir -p "${candidate_path}"
-        cd "${candidate_path}" || return 1
-        local url="https://repo.anaconda.com/miniconda"
-        if [ "${___X_CMD_IN_CHINA_NET:-0}" -eq 1 ]; then
-            url="https://mirrors.tuna.tsinghua.edu.cn/anaconda/miniconda"
-        fi
-
-        env_log info "Downloading $url/$miniconda_filename"
-        if curl --fail --output "$archive_name" "$url/$miniconda_filename"; then
-            env_log info "Download completed python $miniconda_name"
-            return
-        else
-            env_log error "Download failure from $url/${miniconda_filename}"
-            return 1
-        fi
+        return 0
     fi
-)
+
+    local miniconda_filename
+    local compression
+    ___x_cmd_env_python_get_miniconda_filename_and_compression "$version"
+
+    local archive_path="$___X_CMD_ENV_PATH/python/archive/python-$version.$compression"
+    mkdir -p "$(dirname "$archive_path")"
+    local url="https://repo.anaconda.com/miniconda"
+    if [ "${___X_CMD_IN_CHINA_NET:-0}" -eq 1 ]; then
+        url="https://mirrors.tuna.tsinghua.edu.cn/anaconda/miniconda"
+    fi
+
+    env_log info "Downloading $url/$miniconda_filename"
+    if curl --fail --output "$archive_path" "$url/$miniconda_filename"; then
+        env_log info "Download completed python-$version.$compression"
+        return
+    else
+        env_log error "Download failure from $url/${miniconda_filename}"
+        return 1
+    fi
+}
 
 ___x_cmd_env_python_unpack(){
     local version="${1:?Provide python version}"
-    local archive_name
-    ___x_cmd_env_python_get_miniconda_name_and_filename "$version"
+    local miniconda_filename
+    local compression
+    ___x_cmd_env_python_get_miniconda_filename_and_compression "$version"
 
-    env_log info "Unpacking $archive_name"
-    (
-        local candidate_path="$___X_CMD_ENV_PATH/python/versions"
-        mkdir -p "${candidate_path}"
-        cd "$___X_CMD_ENV_PATH/python/archive" || return 1
-        chmod +x "${archive_name}" && \
-        "./${archive_name}" -b -u -p "${candidate_path}/${version}" 1>&2
-    )
+    env_log info "Unpacking python-$version.$compression"
+
+    local versions_path="$___X_CMD_ENV_PATH/python/versions"
+    mkdir -p "${versions_path}"
+    local archive_path="$___X_CMD_ENV_PATH/python/archive/python-$version.$compression"
+    chmod +x "${archive_path}" && \
+    "${archive_path}" -b -u -p "${versions_path}/${version}" 1>&2
 }
 
 
