feat(env): add cross test
link #I4XW5Y

diff --git a/.x-cmd/v0_test b/.x-cmd/v0_test
--- a/.x-cmd/v0_test
+++ b/.x-cmd/v0_test
@@ -1,7 +1,7 @@
 # shellcheck shell=sh disable=SC1072 #source
 
 xrc env
-xrc assert/latest
+xrc assert
 
 test_go(){
     :
@@ -23,11 +23,12 @@ test_maven(){
     :
 }
 
-test_node(){
-    assert_stdout "x env install node" << A
-
-A
-}
+# test_node(){
+#     x env install node
+#     ___x_cmd_assert_stdout "x env current node" << A
+# v17.8.0
+# A
+# }
 
 test_python(){
     :
@@ -45,6 +46,18 @@ test_springboot(){
     :
 }
 
-for testcase in go gradle java kotlin maven node python ruby scala springboot; do
-    "$(test_"$testcase")"
+start_test() {
+    < "$1" awk '$0~/^test_[^\(]+\(\)/{ gsub(/\(\)\{/, "", $0); print $0 }' | while read -r line; do
+        echo "Testing Function: $line"
+        if ! eval "$line"; then
+            printf "\033[0;31m======= Fail at function: %s \033[0m" "$line" >&2
+            break
+        fi
+    done
+}
+
+# go gradle java kotlin maven node python ruby scala springboot
+for testcase in node; do
+    . "$(x wsroot)/.x-cmd/testcases/v0_test_$testcase"
+    # "$(test_"$testcase")"
 done
